//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAT001.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOCUMENTOSAP
    {
        public decimal NUM_DOC { get; set; }
        public string BUKRS { get; set; }
        public Nullable<int> EJERCICIO { get; set; }
        public string CUENTA_C { get; set; }
        public string CUENTA_A { get; set; }
    
        public virtual DOCUMENTO DOCUMENTO { get; set; }
    }
}
