//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAT001.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRESUPUESTOP
    {
        public int ID { get; set; }
        public string ANIO { get; set; }
        public int POS { get; set; }
        public string MES { get; set; }
        public string VERSION { get; set; }
        public string PAIS { get; set; }
        public string MONEDA { get; set; }
        public string MATERIAL { get; set; }
        public string BANNER { get; set; }
        public string CONCEPTO { get; set; }
        public string DATA { get; set; }
    
        public virtual PRESUPUESTOH PRESUPUESTOH { get; set; }
    }
}
