//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAT001.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRESUPUESTOP
    {
        public int ID { get; set; }
        public string ANIO { get; set; }
        public int POS { get; set; }
        public string MES { get; set; }
        public string VERSION { get; set; }
        public string PAIS { get; set; }
        public string MONEDA { get; set; }
        public string MATERIAL { get; set; }
        public string BANNER { get; set; }
        public string ADVER { get; set; }
        public string CONPR { get; set; }
        public string CSHDC { get; set; }
        public string DIRLB { get; set; }
        public string DSTRB { get; set; }
        public string FREEG { get; set; }
        public string GRSLS { get; set; }
        public string NETLB { get; set; }
        public string OVHDF { get; set; }
        public string OVHDV { get; set; }
        public string PKGMT { get; set; }
        public string PMVAR { get; set; }
        public string POP { get; set; }
        public string PURCH { get; set; }
        public string RAWMT { get; set; }
        public string RECUN { get; set; }
        public string RSRDV { get; set; }
        public string TOTCS { get; set; }
    
        public virtual PRESUPUESTOH PRESUPUESTOH { get; set; }
    }
}
