//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAT001.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RANGO
    {
        public decimal EJERCICIO { get; set; }
        public string ID { get; set; }
        public Nullable<decimal> INICIO { get; set; }
        public Nullable<decimal> FIN { get; set; }
        public Nullable<decimal> ACTUAL { get; set; }
        public bool ACTIVO { get; set; }
    
        public virtual RANGONUM RANGONUM { get; set; }
    }
}
