//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAT001.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEXTOCARTAF
    {
        public string SPRAS_ID { get; set; }
        public string E_MAIL { get; set; }
        public string ESTIMADO { get; set; }
        public string CONTROL { get; set; }
        public string FOLIO { get; set; }
        public string PAYER { get; set; }
        public string MONTO { get; set; }
        public string MARCA_AGUA { get; set; }
    }
}
